{
    'name': 'Freeze Header',
    'version': '1.1',
    'description': """Freeze Header""",
    'author': 'Bista Solutions Pvt. Ltd',
    'website': 'http://www.bistasolutions.com',
    'depends': [],
    'category': 'web',
    'sequence': 16,
    'data': ['views/freeze_header.xml'],
    'images': ['images/freezeheader.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
